import { BackgroundLines } from "@/components/ui/background-lines";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Invoice generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BackgroundLines className="flex items-center justify-center w-full flex-col px-4">
          {children}
        </BackgroundLines>
      </body>
    </html>
  );
}
